name: 'Build and Publish'

on:
  release:
    types: [ published ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout PR' 
      uses: actions/checkout@v3
      with:
        ref: main
        token: ${{ secrets.WORKFLOW_PAT }}

    - name: 'Setup Godot'
      run: |
        echo "Downloading Godot..."
        wget -q https://github.com/godotengine/godot/releases/download/3.5.1-stable/Godot_v3.5.1-stable_linux_headless.64.zip
        echo "1 of 2 downloaded..."
        wget -q https://github.com/godotengine/godot/releases/download/3.5.1-stable/Godot_v3.5.1-stable_export_templates.tpz
        echo "Download complete!"
        echo "Setting up directories and unzipping..."
        mkdir -v -p ~/.cache ~/.config/godot ~/.local/share/godot/templates/3.5.1.stable
        unzip Godot_v3.5.1-stable_linux_headless.64.zip
        mv -v Godot_v3.5.1-stable_linux_headless.64 /usr/local/bin/godot
        unzip Godot_v3.5.1-stable_export_templates.tpz
        mv -v templates/* ~/.local/share/godot/templates/3.5.1.stable
        echo "Godot setup complete!"

    - name: 'Build Executables'
      run: |
        cd cliche
        mkdir -v build
        godot -v --export "Windows Desktop"
        godot -v --export "Linux/X11"
        godot -v --export "Mac OSX"

    - name: 'Upload dist files to release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.WORKFLOW_PAT }}
        file: build/*
        tag: ${{ github.ref }}
        file_glob: true
