name: 'Build and Publish'

on:
  release:
    types: [ published ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout PR' 
      uses: actions/checkout@v3
      with:
        ref: main
        token: ${{ secrets.WORKFLOW_PAT }}

    - name: 'Setup Godot'
      run: |
        wget https://github.com/godotengine/godot/releases/download/3.5.1-stable/Godot_v3.5.1-stable_linux_headless.64.zip
        wget https://github.com/godotengine/godot/releases/download/3.5.1-stable/Godot_v3.5.1-stable_export_templates.tpz
        mkdir ~/.cache && mkdir -p ~/.config/godot && mkdir -p ~/.local/share/godot/templates/
        unzip Godot_v3.5.1-stable_linux_headless.64.zip
        mv Godot_v3.5.1-stable_linux_headless.64 /usr/local/bin/godot
        unzip Godot_v3.5.1-stable_export_templates.tpz
        mv templates/* ~/.local/share/godot/templates/

    - name: 'Build Executables'
      strategy:
        matrix:
          os: [ Windows, Linux, MacOSX ]
      run:
        godot -v --export ${{ matrix.os }}

    - name: 'Upload dist files to release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.WORKFLOW_PAT }}
        file: build/*
        tag: ${{ github.ref }}
        file_glob: true
